### ISSUE TITLE
Accept language value en

### ISSUE THREAD

**Issue by eriknikulski** [nhie-io/api#22]
The request `https://api.nhie.io/v1/statements/random?language=en` currently will return
```json
{
"type": "about:blank",
"title": "Bad Request",
"status": 400,
"detail": "English is currently not supported."
}
``` 

this is fucking stupid
PLs FiX :/

**KnObO** wHatcH _BeHaiN_

**Comment by eriknikulski** [comment]
Is there a solution possible at this point of time or does the technology required for this category of problem not exist yet?

The reason I am asking is because a solution to this problem would massively advance the research me and my team are currently doing, which is of national importance.

**Comment by jonasknobloch** [comment]
> Is there a solution possible at this point of time or does the technology required for this category of problem not exist yet?

Yes yes! Rocket science!
